export const openapiExampleContracts = [
  ['examples/auth/challenge-request.json', 'authChallengeRequest'],
  ['examples/auth/challenge-created-201.json', 'authChallengeResponse'],
  ['examples/auth/verification-request.json', 'verifyAuthChallengeRequest'],
  ['examples/auth/verification-response-200.json', 'authVerificationResponse'],
  ['examples/auth/session-authenticated-200.json', 'authSessionResponse'],
  ['examples/auth/session-anonymous-200.json', 'authSessionResponse'],
  ['examples/auth/validation-failed-422.json', 'errorEnvelope'],
  ['examples/auth/code-invalid-401.json', 'errorEnvelope'],
  ['examples/auth/code-expired-401.json', 'errorEnvelope'],
  ['examples/auth/session-expired-401.json', 'errorEnvelope'],
  ['examples/auth/rate-limited-429.json', 'errorEnvelope'],
  ['examples/auth/provider-unavailable-503.json', 'errorEnvelope'],
  [
    'fixtures/catalog/v1/valid/mock-book-config-bundle.json',
    'catalogVersionResponse',
  ],
  ['examples/catalog/catalog-version-unavailable-404.json', 'errorEnvelope'],
  ['examples/pricing/price-quote-request.json', 'priceQuoteRequest'],
  ['examples/pricing/price-quote-created-201.json', 'priceQuote'],
  ['examples/pricing/price-quote-validation-failed-422.json', 'errorEnvelope'],
  ['examples/projects/create-project-request.json', 'createProjectRequest'],
  ['examples/projects/project-detail-200.json', 'projectDetail'],
  ['examples/projects/project-list-200.json', 'projectList'],
  ['examples/projects/auth-required-401.json', 'errorEnvelope'],
  ['examples/projects/csrf-invalid-403.json', 'errorEnvelope'],
  ['examples/projects/idempotency-key-reused-409.json', 'errorEnvelope'],
  ['examples/projects/client-mutation-id-reused-409.json', 'errorEnvelope'],
  ['examples/projects/project-not-found-404.json', 'errorEnvelope'],
  [
    'examples/projects/create-project-validation-failed-422.json',
    'errorEnvelope',
  ],
  ['examples/projects/autosave-request.json', 'saveProjectDocumentRequest'],
  [
    'examples/projects/autosave-response-200.json',
    'saveProjectDocumentResponse',
  ],
  ['examples/projects/revision-conflict-409.json', 'errorEnvelope'],
  ['examples/projects/validation-failed-422.json', 'errorEnvelope'],
  ['examples/uploads/upload-batch-request.json', 'createUploadBatchRequest'],
  [
    'examples/uploads/upload-batch-created-201.json',
    'createUploadBatchResponse',
  ],
  [
    'examples/uploads/complete-upload-request.json',
    'completeAssetUploadRequest',
  ],
  ['examples/uploads/asset-uploaded-200.json', 'asset'],
  ['examples/uploads/asset-list-ready-200.json', 'assetList'],
  ['examples/uploads/renew-upload-200.json', 'uploadInstruction'],
  ['examples/uploads/upload-incomplete-409.json', 'errorEnvelope'],
  ['examples/review/preflight-request.json', 'preflightRunRequest'],
  ['examples/review/preflight-succeeded-201.json', 'preflightRun'],
  ['examples/review/approval-request.json', 'createApprovalRequest'],
  ['examples/review/approval-created-201.json', 'approval'],
  ['examples/render/create-render-job-request.json', 'createRenderJobRequest'],
  ['examples/render/retry-render-job-request.json', 'createRenderJobRequest'],
  ['examples/render/render-job-queued-202.json', 'renderJob'],
  ['examples/render/render-job-succeeded-200.json', 'renderJob'],
  ['examples/render/render-job-failed-200.json', 'renderJob'],
  ['examples/render/approval-outdated-409.json', 'errorEnvelope'],
  ['examples/render/render-profile-unavailable-422.json', 'errorEnvelope'],
  ['examples/orders/create-order-request.json', 'createOrderRequest'],
  ['examples/orders/order-created-201.json', 'order'],
  ['examples/orders/order-list-200.json', 'orderList'],
  ['examples/orders/approval-required-409.json', 'errorEnvelope'],
  ['examples/orders/price-quote-invalid-409.json', 'errorEnvelope'],
  ['examples/orders/order-not-found-404.json', 'errorEnvelope'],
  ['examples/operator/order-detail-200.json', 'operatorOrderDetail'],
  ['examples/operator/access-denied-403.json', 'errorEnvelope'],
] as const
